# Generated by Django 5.2.17 on 2026-10-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('dirección', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('historial', models.JSONField(blank=True, default=list)),
                ('admin', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
